require('@components/header/header.js');
// require('@components/alertbox/alertbox.js');
require('@components/primary-button/primary-button.js');
require('@components/dropdown/dropdown.js');
require('@components/popup/popup.js');
require('@components/input/input.js');
require('@components/checkbox/checkbox.js');
require('@components/textarea/textarea.js');
require('@components/radio-button/radio-button.js');
require('@components/dropdown-multiple-select/dropdown-multiple-select.js');
// require('@pages/vacancies/vacancies-employee/vacancy-card-em/vacancy-card-em.js');